import { IonBackButton, IonButton, IonButtons, IonContent, IonHeader, IonIcon, IonPage, IonSpinner, IonTitle, IonToolbar, useIonAlert, useIonRouter, useIonToast, useIonViewWillEnter } from '@ionic/react';
import { calendarOutline, chevronForwardOutline, personOutline, phonePortraitOutline } from 'ionicons/icons';
import { useEffect, useState } from 'react';
import { clearDeviceAuthentication, getEvent, getParticipantName, listAdminEvents, listMyEvents, saveParticipantName, type MyEvents } from '../lib/store';
import type { BoraEvent } from '../lib/types';
import { calendarDetails } from '../lib/calendar';
import { enablePushReminders, pushReminderState, type PushReminderState } from '../lib/push';

type EventListItem = { event: BoraEvent; confirmed: number };
type EventGroups = { created: EventListItem[]; joined: EventListItem[] };
type ExpandedSections = { created: boolean; joined: boolean };
const expansionStorageKey = 'bora_my_events_expanded';
function initialExpansion(): ExpandedSections { try { const saved = JSON.parse(sessionStorage.getItem(expansionStorageKey) || '{}') as Partial<ExpandedSections>; return { created: Boolean(saved.created), joined: Boolean(saved.joined) }; } catch { return { created: false, joined: false }; } }
function modeLabel(event: BoraEvent) { return event.mode === 'agora' ? 'Bora agora' : event.mode === 'mais-tarde' ? 'Bora essa semana' : 'Bora marcar'; }
function eventStatus(event: BoraEvent) { return event.decidedOption ? 'Definido' : event.votingClosed ? 'Encerrado' : 'Recebendo respostas'; }
function eventDateParts(event: BoraEvent) { const details = calendarDetails(event); if (details) return [details.startsAt.toLocaleDateString('pt-BR', { dateStyle: 'medium' }), details.startsAt.toLocaleTimeString('pt-BR', { timeStyle: 'short' })]; if (event.mode === 'marcar' && event.days[0]) return [event.days[0].label, event.days[0].slots.join(', ')]; return ['Data a combinar', '']; }
function eventTime(event: BoraEvent) { return calendarDetails(event)?.startsAt.getTime(); }
function sortEvents(items: EventListItem[]) { const now = Date.now(); return [...items].sort((a, b) => { const aTime = eventTime(a.event) ?? Number.POSITIVE_INFINITY; const bTime = eventTime(b.event) ?? Number.POSITIVE_INFINITY; const aUpcoming = aTime >= now; const bUpcoming = bTime >= now; if (aUpcoming !== bUpcoming) return aUpcoming ? -1 : 1; return aUpcoming ? aTime - bTime : bTime - aTime; }); }

export default function MyEventsPage() {
  const [toast] = useIonToast(); const router = useIonRouter(); const [presentAlert] = useIonAlert();
  const [events, setEvents] = useState<EventGroups>({ created: [], joined: [] }); const [loading, setLoading] = useState(true);
  const [reminderState, setReminderState] = useState<PushReminderState>('unsupported'); const [expanded, setExpanded] = useState<ExpandedSections>(initialExpansion);
  useEffect(() => { void pushReminderState().then(setReminderState).catch(() => setReminderState('unsupported')); }, []);
  useEffect(() => { sessionStorage.setItem(expansionStorageKey, JSON.stringify(expanded)); }, [expanded]);
  useIonViewWillEnter(() => { let active = true; setLoading(true); void listMyEvents().then(async (result: MyEvents) => { const hydrate = async (event: BoraEvent): Promise<EventListItem> => ({ event, confirmed: (await getEvent(event.slug).catch(() => null))?.votes.filter((vote) => vote.response === 'accept').length || 0 }); const [created, joined] = await Promise.all([Promise.all(result.created.map(hydrate)), Promise.all(result.joined.map(hydrate))]); if (active) setEvents({ created: sortEvents(created), joined: sortEvents(joined) }); }).catch((error) => { if (active) toast({ message: error instanceof Error ? error.message : 'Não foi possível carregar seus Boras.', color: 'danger', duration: 2800 }); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; });
  const adminTokens = new Map(listAdminEvents().map((event) => [event.slug, event.adminToken])); const eventLink = (event: BoraEvent) => `/e/${event.slug}${adminTokens.get(event.slug) ? `?admin=${adminTokens.get(event.slug)}` : ''}`;
  const upcoming = [...events.created, ...events.joined].filter(({ event }, index, all) => { const time = eventTime(event); return time !== undefined && time >= Date.now() && all.findIndex((item) => item.event.id === event.id) === index; }).sort((a, b) => eventTime(a.event)! - eventTime(b.event)!);
  async function enableReminders() { try { setReminderState(await enablePushReminders()); toast({ message: 'Lembretes ativados neste aparelho.', color: 'success', duration: 2600 }); } catch (error) { setReminderState(await pushReminderState().catch((): PushReminderState => 'unsupported')); toast({ message: error instanceof Error ? error.message : 'Não foi possível ativar os lembretes.', color: 'danger', duration: 3500 }); } }
  function removeDeviceAccess() { presentAlert({ header: 'Remover acesso deste aparelho?', message: 'Você deixará de ver seus Boras e acessos de organizador neste aparelho. Use um link de recuperação para voltar depois.', buttons: [{ text: 'Cancelar', role: 'cancel' }, { text: 'Remover acesso', role: 'destructive', handler: () => { clearDeviceAuthentication(); router.push('/home', 'root'); } }] }); }
  function editSavedName() { presentAlert({ header: 'Seu nome', inputs: [{ name: 'name', type: 'text', value: getParticipantName(), placeholder: 'Como você quer aparecer?' }], buttons: [{ text: 'Cancelar', role: 'cancel' }, { text: 'Salvar', handler: (data) => saveParticipantName(String(data.name || '')) }] }); }
  function cards(items: EventListItem[], label: string) { return items.map(({ event, confirmed }) => { const [date, time] = eventDateParts(event); return <button type="button" key={event.id} className="my-event-card" onClick={() => router.push(eventLink(event), 'forward')}><span className="my-event-heading"><span className="event-mode-tag">{modeLabel(event)}</span><span className={`event-status-tag ${event.votingClosed ? 'closed' : ''}`}>{eventStatus(event)}</span><strong>{event.title}</strong></span><span className="my-event-metadata"><span>{date}</span>{time && <span>{time}</span>}<span>{event.place}</span></span><span className="my-event-card-bottom"><span>{label}</span><span>{confirmed} de {event.threshold} confirmaram</span></span><span className="my-event-chevron" aria-hidden="true">›</span></button>; }); }
  function disclosure(title: string, items: EventListItem[], label: string, empty: string, key: keyof ExpandedSections) { const id = `my-events-${key}`; if (!items.length) return <section className="my-events-section disclosure-section"><h2 className="my-events-static-heading">{title}</h2><div id={id} className="my-events-empty"><p>{empty}</p>{key === 'created' && <IonButton fill="clear" routerLink="/create?mode=agora">Criar um Bora</IonButton>}</div></section>; const open = expanded[key]; return <section className="my-events-section disclosure-section"><button type="button" className="my-events-disclosure" aria-expanded={open} aria-controls={id} onClick={() => setExpanded((current) => ({ ...current, [key]: !current[key] }))}><span>{title}</span><span className="disclosure-meta"><b>{items.length}</b><span aria-hidden="true">{open ? '⌃' : '⌄'}</span></span></button><div id={id} hidden={!open}>{cards(items, label)}</div></section>; }
  function reminder() { const description = 'Receba avisos quando um Bora for confirmado, alterado ou estiver próximo.'; if (reminderState === 'subscribed') return <section className="reminder-status-row"><IonIcon icon={calendarOutline} aria-hidden="true" /><span>Lembretes ativos neste aparelho</span></section>; if (reminderState === 'unsupported') return <section className="reminders-card"><div><h2>Lembretes</h2><p>{description}</p><p className="muted">Neste navegador os lembretes não estão disponíveis. No iPhone, talvez seja preciso adicionar o Bora à Tela de Início e abrir o app instalado.</p></div></section>; if (reminderState === 'permission-denied') return <section className="reminders-card"><div><h2>Lembretes</h2><p>Notificações bloqueadas. Altere a permissão nas configurações do navegador ou aparelho para ativar lembretes.</p></div></section>; return <section className="reminders-card"><div><h2>Lembretes</h2><p>{description}</p></div><IonButton fill="outline" onClick={() => void enableReminders()}>Ativar lembretes</IonButton></section>; }
  return <IonPage><IonHeader><IonToolbar><IonButtons slot="start"><IonBackButton defaultHref="/home" /></IonButtons><IonTitle>Meus Boras</IonTitle></IonToolbar></IonHeader><IonContent className="ion-padding form-page"><main className="my-events-container"><section className="my-events-intro"><span className="section-eyebrow">Sua agenda</span><p>Eventos que você criou ou em que está participando.</p></section>{loading ? <div className="center"><IonSpinner /><p>Carregando...</p></div> : <><section className="my-events-section"><div className="my-events-section-heading"><h2>Próximos Boras</h2><span>{upcoming.length}</span></div>{upcoming.length ? cards(upcoming, 'Você confirmou') : <div className="my-events-empty"><p>Quando um Bora tiver data e horário definidos, ele aparecerá aqui.</p></div>}</section>{reminder()}{disclosure('Criados por mim', events.created, 'Organizador', 'Você ainda não criou nenhum Bora.', 'created')}{disclosure('Participo', events.joined, 'Convidado', 'Os Boras em que você responder aparecerão aqui. Abra um link de convite para participar.', 'joined')}</>}<div className="device-access-actions"><IonButton fill="clear" className="device-access-row" onClick={editSavedName}><IonIcon slot="start" icon={personOutline} aria-hidden="true" /><span className="device-access-copy"><strong>Seu nome</strong><small>{getParticipantName() || 'Adicionar ou corrigir seu nome.'}</small></span><IonIcon slot="end" icon={chevronForwardOutline} aria-hidden="true" /></IonButton><IonButton fill="clear" className="device-access-row" routerLink="/recover"><IonIcon slot="start" icon={phonePortraitOutline} aria-hidden="true" /><span className="device-access-copy"><strong>Usar meus Boras em outro dispositivo</strong><small>Crie um link de acesso para outro aparelho.</small></span><IonIcon slot="end" icon={chevronForwardOutline} aria-hidden="true" /></IonButton><IonButton fill="clear" color="danger" className="remove-device-action" onClick={removeDeviceAccess}>Remover acesso deste aparelho</IonButton></div></main></IonContent></IonPage>;
}
