import { IonBackButton, IonButton, IonButtons, IonCard, IonCardContent, IonCheckbox, IonContent, IonHeader, IonIcon, IonItem, IonLabel, IonPage, IonSpinner, IonTitle, IonToolbar, useIonToast } from '@ionic/react';
import { shieldCheckmarkOutline } from 'ionicons/icons';
import QRCode from 'qrcode';
import { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { clearDeviceAuthentication, createRecoveryLink, hasRegisteredParticipant, recoverParticipant, restoreAdminEvents, restoreParticipantId, restoreParticipantName, type AdminEventAccess } from '../lib/store';

function adminEventsFromFragment(hash: string): AdminEventAccess[] { try { const value = new URLSearchParams(hash.replace(/^#/, '')).get('admin'); const events = value ? JSON.parse(value) : []; return Array.isArray(events) ? events : []; } catch { return []; } }
function participantNameFromFragment(hash: string) { return new URLSearchParams(hash.replace(/^#/, '')).get('name') || ''; }

export default function RecoverPage() {
  const [status, setStatus] = useState<'loading' | 'confirm' | 'ready' | 'error' | 'transfer'>('loading');
  const [adminAccessRestored, setAdminAccessRestored] = useState(false); const [includeAdminAccess, setIncludeAdminAccess] = useState(false); const [creating, setCreating] = useState(false); const [link, setLink] = useState(''); const [qrCode, setQrCode] = useState('');
  const [toast] = useIonToast(); const location = useLocation();
  async function recoverFromLink() { const token = new URLSearchParams(location.search).get('token'); if (!token) { setStatus('transfer'); return; } const adminEvents = adminEventsFromFragment(location.hash); const participantName = participantNameFromFragment(location.hash); setStatus('loading'); try { const participantId = await recoverParticipant(token); clearDeviceAuthentication(); restoreParticipantId(participantId); restoreAdminEvents(adminEvents); if (participantName) restoreParticipantName(participantName); setAdminAccessRestored(adminEvents.length > 0); window.history.replaceState({}, '', '/recover'); setStatus('ready'); } catch { setStatus('error'); } }
  function cancelRecovery() { window.history.replaceState({}, '', '/recover'); setStatus('transfer'); }
  useEffect(() => { const token = new URLSearchParams(location.search).get('token'); if (!token) { setStatus('transfer'); return; } if (hasRegisteredParticipant()) setStatus('confirm'); else void recoverFromLink(); }, [location.search, location.hash]);
  useEffect(() => { if (!link) { setQrCode(''); return; } void QRCode.toDataURL(link, { width: 220, margin: 1, errorCorrectionLevel: 'M' }).then(setQrCode).catch(() => setQrCode('')); }, [link]);
  async function createLink() { setCreating(true); try { const nextLink = await createRecoveryLink(includeAdminAccess); setLink(nextLink); toast({ message: 'Link criado.', color: 'success', duration: 1800 }); } catch (error) { toast({ message: error instanceof Error ? error.message : 'Não foi possível criar o link.', color: 'danger', duration: 2800 }); } finally { setCreating(false); } }
  async function copyLink() { try { await navigator.clipboard.writeText(link); toast({ message: 'Link copiado.', color: 'success', duration: 1800 }); } catch { toast({ message: 'Não foi possível copiar o link.', color: 'danger', duration: 2200 }); } }
  async function shareLink() { if (navigator.share) { try { await navigator.share({ title: 'Meus Boras', text: 'Use meus Boras em outro dispositivo', url: link }); return; } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') return; } } await copyLink(); }
  return <IonPage><IonHeader><IonToolbar><IonButtons slot="start"><IonBackButton defaultHref="/my-events" text="Voltar" /></IonButtons><IonTitle>{status === 'transfer' ? 'Usar meus Boras em outro dispositivo' : 'Recuperar meus Boras'}</IonTitle></IonToolbar></IonHeader><IonContent className="ion-padding form-page"><main className="recovery-container"><IonCard className="recovery-card"><IonCardContent>
    {status === 'loading' && <><IonSpinner /><h1>Recuperando seus Boras…</h1><p>Estamos restaurando sua lista neste aparelho.</p></>}
    {status === 'confirm' && <><h1>Usar este link de recuperação?</h1><p>Ele vai remover os Boras registrados neste aparelho e substituí-los pelos deste link.</p><IonButton expand="block" onClick={() => void recoverFromLink()}>Usar link</IonButton><IonButton expand="block" fill="clear" onClick={cancelRecovery}>Cancelar</IonButton></>}
    {status === 'ready' && <><h1>Pronto!</h1><p>Seus Boras foram restaurados neste aparelho.{adminAccessRestored ? ' Seus controles de organizador também foram restaurados.' : ' Seus links de administrador continuam privados no aparelho original.'}</p><IonButton expand="block" routerLink="/my-events">Ver meus Boras</IonButton></>}
    {status === 'error' && <><h1>Não foi possível recuperar</h1><p>Esse link é inválido ou foi substituído por um novo.</p><IonButton expand="block" routerLink="/home">Voltar para o início</IonButton></>}
    {status === 'transfer' && <><p className="recovery-lead">Crie um link para acessar seus Boras em outro aparelho. Este aparelho continuará com acesso normalmente.</p><IonButton expand="block" onClick={() => void createLink()} disabled={creating}>{creating ? 'Criando link…' : 'Criar link de acesso'}</IonButton><details className="recovery-options"><summary>Opções avançadas</summary><IonItem button detail={false} lines="none" className="recovery-admin-option" onClick={() => setIncludeAdminAccess((current) => !current)}><IonCheckbox slot="start" checked={includeAdminAccess} onClick={(event) => event.stopPropagation()} onIonChange={(event) => setIncludeAdminAccess(event.detail.checked)} /><IonLabel>Incluir controles de organizador<small>Permite editar, encerrar e excluir os eventos que você criou.</small></IonLabel></IonItem>{includeAdminAccess && <p className="recovery-security-warning"><IonIcon icon={shieldCheckmarkOutline} aria-hidden="true" />Quem receber este link poderá editar e excluir os eventos que você organizou.</p>}</details>{link && <section className="recovery-created-link"><p>Abra a câmera do outro aparelho para escanear o código, ou compartilhe o link.</p>{qrCode && <img className="recovery-qr-code" src={qrCode} alt="QR code para abrir seus Boras em outro dispositivo" />}<div className="recovery-link-actions"><IonButton onClick={() => void shareLink()}>Compartilhar</IonButton><IonButton fill="outline" onClick={() => void copyLink()}>Copiar link</IonButton></div></section>}</>}
  </IonCardContent></IonCard></main></IonContent></IonPage>;
}
